# NOTE: Generated By HttpRunner v3.1.4
# FROM: har\mubu.har
import sys
from pathlib import Path
import pytest
from httprunner import Parameters

sys.path.insert(0, str(Path(__file__).parent.parent))
from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase
from demo.testcases.login_test import (
    TestCaseMubuLogin as MubuLogin,
)


class TestCaseCreateDoc(HttpRunner):
    @pytest.mark.parametrize(
        "param",
        Parameters(
            {
                "docTitle": "${gen_doc_titles(3)}",
                "phone-password":"${parameterize(data/account.csv)}"
            }
        )
    )
    def test_start(self, param):
        super().test_start(param)

    config = (
        Config("testcase description")
            .variables(**{
            "phone": "13554170217",
            "password": "919299",
            "memberId": "8015102001446481",
            "host": "mubu.com",
            "docTitle": "${gen_random_title()}",
        })
            .base_url("https://$host")
            .verify(False)
            .export("docTitle", "docID")
    )

    teststeps = [
        Step(
            RunTestCase("login")
                .with_variables(**{
                "phone": "13554170218",
                "password": "919290",
                "host": "mubu.com"
            })
                .call(MubuLogin)
                .export("JwtToken", "userId")
        ),
        Step(
            RunRequest("/v3/api/list/create_doc")
                .post("https://api2.mubu.com/v3/api/list/create_doc")
                .with_headers(
                **{
                    "content-length": "25",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "${JwtToken}",
                    "content-type": "application/json;charset=UTF-8",
                    "user-agent": "HttpRunner/${get_httprunner_version()}",
                    "x-request-id": "646ba035-1b41-4708-8a44-7df3bc8db6d4",
                    "version": "3.0.0",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/app",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
                .with_json({"folderId": "0", "type": 0})
                .extract()
                .with_jmespath("body.data.id", "docID")
                .validate()
                .assert_equal("status_code", 200)
                .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/list/item_count")
                .post("https://api2.mubu.com/v3/api/list/item_count")
                .with_headers(
                **{
                    "content-length": "30",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "${JwtToken}",
                    "content-type": "application/json;charset=UTF-8",
                    "user-agent": "HttpRunner/${get_httprunner_version()}",
                    "x-request-id": "8e3a8bf8-0deb-4c56-9daf-9988a2220a0f",
                    "version": "3.0.0",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/app/edit/home/${docID}",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
                .with_json({"folderId": 0, "source": "home"})
                .validate()
                .assert_equal("status_code", 200)
                .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/user/current_level")
                .post("https://api2.mubu.com/v3/api/user/current_level")
                .with_headers(
                **{
                    "content-length": "29",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "${JwtToken}",
                    "content-type": "application/json;charset=UTF-8",
                    "user-agent": "HttpRunner/${get_httprunner_version()}",
                    "x-request-id": "f6c2e9a4-eccb-445e-9596-f9f52b6a5e76",
                    "version": "3.0.0",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/app/edit/home/${docID}",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
                .with_json({"document_id": "${docID}"})
                .validate()
                .assert_equal("status_code", 200)
                .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/document/edit/get")
                .post("https://api2.mubu.com/v3/api/document/edit/get")
                .with_headers(
                **{
                    "content-length": "37",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "${JwtToken}",
                    "content-type": "application/json;charset=UTF-8",
                    "user-agent": "HttpRunner/${get_httprunner_version()}",
                    "x-request-id": "ac3d4499-9218-44f4-95ab-601e19bdefcf",
                    "version": "3.0.0",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/app/edit/home/${docID}",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
                .with_json({"docId": "${docID}", "password": ""})
                .validate()
                .assert_equal("status_code", 200)
                .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/refer/doc/list")
                .post("https://api2.mubu.com/v3/api/refer/doc/list")
                .with_headers(
                **{
                    "content-length": "29",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "${JwtToken}",
                    "user-agent": "HttpRunner/${get_httprunner_version()}",
                    "x-request-id": "77fceaf9-5ffb-4d35-833f-4aa33a269306",
                    "content-type": "application/json;charset=UTF-8",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/app/edit/home/${docID}",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
                .with_json({"targetDocId": "${docID}"})
                .validate()
                .assert_equal("status_code", 200)
                .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/colla/register")
                .get("https://api2.mubu.com/v3/api/colla/register")
                .with_headers(
                **{
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "${JwtToken}",
                    "user-agent": "HttpRunner/${get_httprunner_version()}",
                    "x-request-id": "53e2c622-e0db-4cd5-8181-9ea9cc30f808",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/app/edit/home/${docID}",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
                .validate()
                .assert_equal("status_code", 200)
                .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/colla/members")
                .options("https://api2.mubu.com/v3/api/colla/members")
                .with_params(
                **{"memberId": "${memberId}", "documentId": "${docID}"}
            )
                .with_headers(
                **{
                    "accept": "*/*",
                    "access-control-request-method": "GET",
                    "access-control-request-headers": "data-unique-id,jwt-token,request-id,x-request-id",
                    "origin": "https://mubu.com",
                    "user-agent": "HttpRunner/${get_httprunner_version()}",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/app/edit/home/${docID}",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
                .validate()
                .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/v3/api/colla/members")
                .get("https://api2.mubu.com/v3/api/colla/members")
                .with_params(
                **{"memberId": "${memberId}", "documentId": "${docID}"}
            )
                .with_headers(
                **{
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "${JwtToken}",
                    "request-id": "members:${memberId}:1614129095734",
                    "user-agent": "HttpRunner/${get_httprunner_version()}",
                    "x-request-id": "fa132023-1d3c-41c4-9232-3fe2c1cda2e2",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/app/edit/home/${docID}",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
                .validate()
                .assert_equal("status_code", 200)
                .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/colla/message")
                .post("https://api2.mubu.com/v3/api/colla/message")
                .with_headers(
                **{
                    "content-length": "356",
                    "member-id": "${memberId}",
                    "user-agent": "HttpRunner/${get_httprunner_version()}",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "${JwtToken}",
                    "request-id": "MESSAGE:${userId}:${memberId}:3",
                    "x-request-id": "bdf00704-7af1-45b1-a442-8c319b658538",
                    "version": "3.0.0",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/app/edit/home/${docID}",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
                .with_json(
                {
                    "engineType": "MUBU",
                    "messageType": "BROADCAST",
                    "reqId": 3,
                    "requestId": "MESSAGE:${userId}:${memberId}:3",
                    "token": "${docID}",
                    "data": {
                        "message": {
                            "type": "CHANGE",
                            "documentId": "${docID}",
                            "version": 0,
                            "content": [
                                {"name": "nameChanged", "title": "$docTitle", "original": ""}
                            ],
                        }
                    },
                    "context": {
                        "os": "Windows",
                        "osVersion": "NT 6.1",
                        "appVersion": "default",
                        "platform": "web",
                    },
                }
            )
                .validate()
                .assert_equal("status_code", 200)
                .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/refer/search_refers")
                .post("https://api2.mubu.com/v3/api/refer/search_refers")
                .with_headers(
                **{
                    "content-length": "51",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "${JwtToken}",
                    "user-agent": "HttpRunner/${get_httprunner_version()}",
                    "x-request-id": "4efb1745-2bb4-44bc-9058-bc180d09ccd6",
                    "content-type": "application/json;charset=UTF-8",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/app/edit/home/${docID}",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
                .with_json({"docId": "${docID}", "keywords": "喵", "option": 1})
                .validate()
                .assert_equal("status_code", 200)
                .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/colla/message")
                .post("https://api2.mubu.com/v3/api/colla/message")
                .with_headers(
                **{
                    "content-length": "362",
                    "member-id": "${memberId}",
                    "user-agent": "HttpRunner/${get_httprunner_version()}",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "${JwtToken}",
                    "request-id": "MESSAGE:${userId}:${memberId}:5",
                    "x-request-id": "ed77cc69-83f6-433f-b69d-2975b3ab55a8",
                    "version": "3.0.0",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/app/edit/home/${docID}",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
                .with_json(
                {
                    "engineType": "MUBU",
                    "messageType": "BROADCAST",
                    "reqId": 5,
                    "requestId": "MESSAGE:${userId}:${memberId}:5",
                    "token": "${docID}",
                    "data": {
                        "message": {
                            "type": "CHANGE",
                            "documentId": "${docID}",
                            "version": 1,
                            "content": [
                                {"name": "nameChanged", "title": "$docTitle", "original": ""}
                            ],
                        }
                    },
                    "context": {
                        "os": "Windows",
                        "osVersion": "NT 6.1",
                        "appVersion": "default",
                        "platform": "web",
                    },
                }
            )
                .validate()
                .assert_equal("status_code", 200)
                .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/refer/search_refers")
                .post("https://api2.mubu.com/v3/api/refer/search_refers")
                .with_headers(
                **{
                    "content-length": "54",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "${JwtToken}",
                    "user-agent": "HttpRunner/${get_httprunner_version()}",
                    "x-request-id": "0fcff788-4d4d-4b2b-8d7e-33b52943faa4",
                    "content-type": "application/json;charset=UTF-8",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/app/edit/home/${docID}",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
                .with_json({"docId": "${docID}", "keywords": "喵喵", "option": 1})
                .validate()
                .assert_equal("status_code", 200)
                .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/colla/message")
                .post("https://api2.mubu.com/v3/api/colla/message")
                .with_headers(
                **{
                    "content-length": "368",
                    "member-id": "${memberId}",
                    "user-agent": "HttpRunner/${get_httprunner_version()}",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "${JwtToken}",
                    "request-id": "MESSAGE:${userId}:${memberId}:7",
                    "x-request-id": "01ef7193-ca4e-490c-84a5-b3e93d9f0195",
                    "version": "3.0.0",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/app/edit/home/${docID}",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
                .with_json(
                {
                    "engineType": "MUBU",
                    "messageType": "BROADCAST",
                    "reqId": 7,
                    "requestId": "MESSAGE:${userId}:${memberId}:7",
                    "token": "${docID}",
                    "data": {
                        "message": {
                            "type": "CHANGE",
                            "documentId": "${docID}",
                            "version": 2,
                            "content": [
                                {
                                    "name": "nameChanged",
                                    "title": "$docTitle",
                                    "original": "",
                                }
                            ],
                        }
                    },
                    "context": {
                        "os": "Windows",
                        "osVersion": "NT 6.1",
                        "appVersion": "default",
                        "platform": "web",
                    },
                }
            )
                .validate()
                .assert_equal("status_code", 200)
                .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/colla/message")
                .post("https://api2.mubu.com/v3/api/colla/message")
                .with_headers(
                **{
                    "content-length": "458",
                    "member-id": "${memberId}",
                    "user-agent": "HttpRunner/${get_httprunner_version()}",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "${JwtToken}",
                    "request-id": "MESSAGE:${userId}:${memberId}:9",
                    "x-request-id": "7f4b3c9d-931f-476b-a2e2-d24ffd3fe5bb",
                    "version": "3.0.0",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/app/edit/home/${docID}",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
                .with_json(
                {
                    "engineType": "MUBU",
                    "messageType": "BROADCAST",
                    "reqId": 9,
                    "requestId": "MESSAGE:${userId}:${memberId}:9",
                    "token": "${docID}",
                    "data": {
                        "message": {
                            "type": "CHANGE",
                            "documentId": "${docID}",
                            "version": 3,
                            "content": [
                                {
                                    "name": "create",
                                    "created": [
                                        {
                                            "index": 0,
                                            "parentId": None,
                                            "node": {
                                                "id": "QexuqdCwy8",
                                                "text": "",
                                                "modified": 1614129101566,
                                                "children": [],
                                            },
                                            "path": ["nodes", 0],
                                        }
                                    ],
                                }
                            ],
                        }
                    },
                    "context": {
                        "os": "Windows",
                        "osVersion": "NT 6.1",
                        "appVersion": "default",
                        "platform": "web",
                    },
                }
            )
                .validate()
                .assert_equal("status_code", 200)
                .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/refer/search_refers")
                .post("https://api2.mubu.com/v3/api/refer/search_refers")
                .with_headers(
                **{
                    "content-length": "57",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "${JwtToken}",
                    "user-agent": "HttpRunner/${get_httprunner_version()}",
                    "x-request-id": "389f9e30-437c-4207-86d3-696771a8e85a",
                    "content-type": "application/json;charset=UTF-8",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/app/edit/home/${docID}",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
                .with_json({"docId": "${docID}", "keywords": "喵喵喵", "option": 1})
                .validate()
                .assert_equal("status_code", 200)
                .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/colla/message")
                .post("https://api2.mubu.com/v3/api/colla/message")
                .with_headers(
                **{
                    "content-length": "505",
                    "member-id": "${memberId}",
                    "user-agent": "HttpRunner/${get_httprunner_version()}",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "${JwtToken}",
                    "request-id": "MESSAGE:${userId}:${memberId}:11",
                    "x-request-id": "a1a174cd-e559-4f3c-bb0b-8d76fffca418",
                    "version": "3.0.0",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/app/edit/home/${docID}",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
                .with_json(
                {
                    "engineType": "MUBU",
                    "messageType": "BROADCAST",
                    "reqId": 11,
                    "requestId": "MESSAGE:${userId}:${memberId}:11",
                    "token": "${docID}",
                    "data": {
                        "message": {
                            "type": "CHANGE",
                            "documentId": "${docID}",
                            "version": 4,
                            "content": [
                                {
                                    "name": "update",
                                    "updated": [
                                        {
                                            "updated": {
                                                "id": "QexuqdCwy8",
                                                "text": "<span>喵</span>",
                                                "modified": 1614129103314,
                                            },
                                            "original": {
                                                "id": "QexuqdCwy8",
                                                "text": "",
                                                "modified": 1614129101566,
                                            },
                                            "path": ["nodes", 0],
                                        }
                                    ],
                                }
                            ],
                        }
                    },
                    "context": {
                        "os": "Windows",
                        "osVersion": "NT 6.1",
                        "appVersion": "default",
                        "platform": "web",
                    },
                }
            )
                .validate()
                .assert_equal("status_code", 200)
                .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/colla/message")
                .post("https://api2.mubu.com/v3/api/colla/message")
                .with_headers(
                **{
                    "content-length": "677",
                    "member-id": "${memberId}",
                    "user-agent": "HttpRunner/${get_httprunner_version()}",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "${JwtToken}",
                    "request-id": "MESSAGE:${userId}:${memberId}:13",
                    "x-request-id": "e7a550db-cc28-4e93-8da6-f1b023c96ced",
                    "version": "3.0.0",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/app/edit/home/${docID}",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
                .with_json(
                {
                    "engineType": "MUBU",
                    "messageType": "BROADCAST",
                    "reqId": 13,
                    "requestId": "MESSAGE:${userId}:${memberId}:13",
                    "token": "${docID}",
                    "data": {
                        "message": {
                            "type": "CHANGE",
                            "documentId": "${docID}",
                            "version": 5,
                            "content": [
                                {
                                    "name": "update",
                                    "updated": [
                                        {
                                            "updated": {
                                                "id": "QexuqdCwy8",
                                                "text": "<span>喵喵</span>",
                                                "modified": 1614129104574,
                                            },
                                            "original": {
                                                "id": "QexuqdCwy8",
                                                "text": "<span>喵</span>",
                                                "modified": 1614129103314,
                                            },
                                            "path": ["nodes", 0],
                                        }
                                    ],
                                },
                                {
                                    "name": "create",
                                    "created": [
                                        {
                                            "index": 1,
                                            "parentId": None,
                                            "node": {
                                                "id": "DySzv3DORp",
                                                "text": "",
                                                "modified": 1614129105025,
                                                "children": [],
                                            },
                                            "path": ["nodes", 1],
                                        }
                                    ],
                                },
                            ],
                        }
                    },
                    "context": {
                        "os": "Windows",
                        "osVersion": "NT 6.1",
                        "appVersion": "default",
                        "platform": "web",
                    },
                }
            )
                .validate()
                .assert_equal("status_code", 200)
                .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/colla/message")
                .post("https://api2.mubu.com/v3/api/colla/message")
                .with_headers(
                **{
                    "content-length": "505",
                    "member-id": "${memberId}",
                    "user-agent": "HttpRunner/${get_httprunner_version()}",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "${JwtToken}",
                    "request-id": "MESSAGE:${userId}:${memberId}:15",
                    "x-request-id": "4ef7c754-4803-40b8-96e7-81d4e4acccb2",
                    "version": "3.0.0",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/app/edit/home/${docID}",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
                .with_json(
                {
                    "engineType": "MUBU",
                    "messageType": "BROADCAST",
                    "reqId": 15,
                    "requestId": "MESSAGE:${userId}:${memberId}:15",
                    "token": "${docID}",
                    "data": {
                        "message": {
                            "type": "CHANGE",
                            "documentId": "${docID}",
                            "version": 6,
                            "content": [
                                {
                                    "name": "update",
                                    "updated": [
                                        {
                                            "updated": {
                                                "id": "DySzv3DORp",
                                                "text": "<span>喵</span>",
                                                "modified": 1614129106761,
                                            },
                                            "original": {
                                                "id": "DySzv3DORp",
                                                "text": "",
                                                "modified": 1614129105025,
                                            },
                                            "path": ["nodes", 1],
                                        }
                                    ],
                                }
                            ],
                        }
                    },
                    "context": {
                        "os": "Windows",
                        "osVersion": "NT 6.1",
                        "appVersion": "default",
                        "platform": "web",
                    },
                }
            )
                .validate()
                .assert_equal("status_code", 200)
                .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/list/item_count")
                .post("https://api2.mubu.com/v3/api/list/item_count")
                .with_headers(
                **{
                    "content-length": "30",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "${JwtToken}",
                    "content-type": "application/json;charset=UTF-8",
                    "user-agent": "HttpRunner/${get_httprunner_version()}",
                    "x-request-id": "2401da2c-3a4f-4a12-b449-dc9d03b528d9",
                    "version": "3.0.0",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/app",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
                .with_json({"folderId": 0, "source": "home"})
                .validate()
                .assert_equal("status_code", 200)
                .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/colla/message")
                .post("https://api2.mubu.com/v3/api/colla/message")
                .with_headers(
                **{
                    "content-length": "227",
                    "member-id": "${memberId}",
                    "user-agent": "HttpRunner/${get_httprunner_version()}",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "${JwtToken}",
                    "request-id": "MESSAGE:${userId}:${memberId}:17",
                    "x-request-id": "2b048a79-73c1-4450-9d6c-55c4b3b5ee5a",
                    "version": "3.0.0",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/app",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
                .with_json(
                {
                    "engineType": "MUBU",
                    "messageType": "UNWATCH",
                    "reqId": 17,
                    "requestId": "MESSAGE:${userId}:${memberId}:17",
                    "token": "${docID}",
                    "data": {},
                    "context": {
                        "os": "Windows",
                        "osVersion": "NT 6.1",
                        "appVersion": "default",
                        "platform": "web",
                    },
                }
            )
                .validate()
                .assert_equal("status_code", 200)
                .assert_equal("body.code", 0)
        ),
    ]


if __name__ == "__main__":
    TestCaseCreateDoc().test_start()
